### ISSUE TITLE
Indexerror

### ISSUE THREAD

**Issue by jyotikhetan** [jina-ai/executor-image-paddlepaddle-ocr#9] opened 2021-11-14 19:42 UTC
I am trying to implement for image document..!! But getting this error.. what could be the possible reason. Please help

[2021/11/15 00:56:24] root INFO: dt_boxes num : 5, elapse : 0.6937777996063232
[2021/11/15 00:56:24] root INFO: cls num  : 5, elapse : 0.023710966110229492
      executor0@28233[E]:IndexError('list index out of range')
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 250, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 236, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 203, in _handle
    peapod_name=self.name,
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 163, in handle
    field='groundtruths',
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/jina/executors/__init__.py", line 200, in __call__
    self, **kwargs
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/jina/executors/decorators.py", line 105, in arg_wrapper
    return fn(*args, **kwargs)
  File "/home/jyoti/.jina/hub-packages/78yp7etm/executor.py", line 62, in extract
    for r in self.model.ocr(source_fn, cls=True):
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/paddleocr/paddleocr.py", line 300, in ocr
    dt_boxes, rec_res = self.__call__(img)
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/paddleocr/tools/infer/predict_system.py", line 106, in __call__
    rec_res, elapse = self.text_recognizer(img_crop_list)
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/paddleocr/tools/infer/predict_rec.py", line 115, in __call__
    rec_result = self.postprocess_op(preds)
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 110, in __call__
    text = self.decode(preds_idx, preds_prob)
  File "/home/jyoti/jina2/jienv/lib/python3.7/site-packages/paddleocr/ppocr/postprocess/rec_postprocess.py", line 80, in decode
    idx])])
IndexError: list index out of range

Process finished with exit code 0

**Comment by nan-wang** [comment] 2021-11-15 08:25
@jyotikhetan hey, there. Thanks for your issue. Is it possible to share the image that you are processing? It seems to be an up-stream issue with https://github.com/PaddlePaddle/PaddleOCR

**Comment by jyotikhetan** [comment] 2021-11-16 06:18
hi @nan-wang Thank you for reverting back.!!
![test1](https://user-images.githubusercontent.com/52456132/141931795-32669bd6-e729-430c-958a-598b5e8420dd.png)
.
As I am not sure why it is throwing this error. Is it because am I making some mistake in Jina pipeline or what it is?

**Comment by nan-wang** [comment] 2021-11-17 08:22
> Jina pipeline
Would you please share your codes?

**Comment by azayz** [comment] 2021-11-17 09:39
Can you share your pipeline and versions so we can debug this :)

**Comment by jyotikhetan** [comment] 2021-11-18 06:43
This piece of code I tried this on...!!

from jina import Flow,Document,DocumentArray


f = Flow().add(uses='jinahub://PaddlepaddleOCR')

docs = DocumentArray()
doc = Document(uri='/home/jyoti/Desktop/test1.png')
docs.append(doc)

with f:
    f.post(on='/extract', inputs=docs, on_done=lambda resp: print(resp.docs[0].text))

Thank you..

**Comment by azayz** [comment] 2021-11-29 09:33
I used the exact pipeline that you used with the same image and I can't seem to reproduce your error.

- Can you check if you are reading the image correctly ? 
- Can you print the versions of jina, paddlepaddle and paddleocr ? 
- Can you use breakpoint in your IDE and see exactly where it goes wrong ? 

My versions are : 
jina==2.4.7
paddleocr==2.3.0.1
paddlepaddle==2.1.3

**Comment by jyotikhetan** [comment] 2021-11-30 05:14
hi @azayz Thank you for the solution..!! Now I am able to run flow...!! It was a version issue...

**Comment by JoanFM** [comment] 2021-11-30 06:12
Closing the issue as it seems to be solved

**Closed by JoanFM** 2021-11-30 06:12 UTC
